- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours # mono
  startingGear: SeniorOfficerGear
  icon: JobIconSergeant
  supervisors: job-supervisors-sheriff
  weight: 140
  displayWeight: 50
  assignedCompany: TSF
  canBeAntag: false
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Medical
  - Chemistry
  - TsfmcEngineering
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer
#    - ShipVoucherNfsdSergeant # Mono
    - RadioHandheldNF # Mono
