name: PR Changelogs
concurrency: commit_action-${{ github.event.pull_request.base.ref }} # Mono
on:
  pull_request_target:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_DIR: Resources/Changelog/Monolith.yml # Mono
  PR_NUMBER: ${{ github.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Checkout Base Branch # Mono
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: "${{ github.event.pull_request.base.ref }}" # Mono

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/changelog"
          npm install
        shell: bash

      - name: Generate Changelog
        run: |
          cd "Tools/changelog"
          node changelog.js
        shell: bash

      - name: Commit Changelog
        run: |
          git pull origin "${{ github.event.pull_request.base.ref }}"
          git add "${{ env.CHANGELOG_DIR }}"
          git commit -m "Automated Changelog (#${{ env.PR_NUMBER }})"
          git push origin "${{ github.event.pull_request.base.ref }}"
        shell: bash
        continue-on-error: true
